# this is config file for the Supplements plugin

# settings for discord command
# 1st line
discordLine1: "------------------------------------"
# regular text on 2nd line
discordText1: "&3Join our discord server:"
# clickable text on 2nd line
discordLinkText: "&6 CLICK ME"
# discord url
discordLinkAddress: "https://discord.gg/"
# regular text on 2nd line
discordText2: "&3 <<"
# last line
discordLine2: "------------------------------------"

# Join and Leave messages
# enable different messages for new players
uniqueFirstJoin: true
# message for new players
uniqueJoin: "&6{PLAYER} &eis new to the server, say hi!"
# player join message
playerJoin: "&6{PLAYER} &ejoined the server."
# player leave message
playerLeft: "&6{PLAYER} &eleft the server."
# use {PLAYER} to display players name

# Teleport to spawn on join
# Teleport players to spawn when they join the server
teleportOnJoin: false
# Teleport new players to spawn when they join for the first time
# (If teleportOnJoin: true, teleportNewPlayers will be also true)
teleportNewPlayers: true

# Teleport to spawn on death
# Teleport players to spawn always when they die
always: false
# Teleport players to spawn when they don't have a bed or respawn anchor
# (If always: true, noRespawnPoint will be also true)
noRespawnPoint: true

# home command
# number of homes per player
homes: 1
# player has reached max number of homes
maxHomes: "&cYou have reached the max amount of homes!"
# player sets home without specifying name (doesn't apply for first home)
missingHomeName: "&cUse /sethome <homeName> to set your home."
# player set home successfully
homeSet: "&aHome set successfully."
# player does not have a home
noHomes: "&cYou must set your home first."
# player gets teleported to home
tpHome: "&aSuccessfully teleported to your home."
# requested home not found
homeNotFound: "&cRequested home could not be found."
# home deleted
homeRemoved: "&aHome &cDELETED&a successfully."
# player tried deleting while he didn't have one
noHomeToRemove: "&cYou have no homes to remove!"
# player did not specify home he wants to delete
specifyHomeToRemove: "&cYou have to specify home to delete!"
# player tried to delete non-existing home
homeToRemoveNotFound: "&cHome you want to delete does not exist!"

# Spawn command messages
# set spawn command
setSpawn: "&aSpawn set successfully."
# teleport to spawn
teleportedToSpawn: "&aTeleported to spawn."
# couldn't teleport to spawn because spawn does not exist
spawnNotExist: "&cSpawn does not exist!"
