# this is config file for the Supplements plugin

# settings for discord command
# clickable text
discordLinkText: "&6 CLICK ME"
# discord url
discordURL: "https://discord.gg/"
# discord message
discord: "
  ------------------------------------\n
  &3Join our discord server:{LINK} &3<<\n
  &f------------------------------------
  "
# use {LINK} to display clickable text (discordLinkText)
# use \n to create new line

# Join and Leave messages
# enable different messages for new players
uniqueFirstJoin: true
# message for new players
uniqueJoin: "&6{PLAYER} &eis new to the server, say hi!"
# player join message
playerJoin: "&6{PLAYER} &ejoined the server."
# player leave message
playerLeft: "&6{PLAYER} &eleft the server."
# use {PLAYER} to display players name

# Teleport to spawn on join
# Teleport players to spawn when they join the server
teleportOnJoin: false
# Teleport new players to spawn when they join for the first time
# (If teleportOnJoin: true, teleportNewPlayers will be also true)
teleportNewPlayers: true

# Teleport to spawn on death
# Teleport players to spawn always when they die
always: false
# Teleport players to spawn when they don't have a bed or respawn anchor
# (If always: true, noRespawnPoint will be also true)
noRespawnPoint: true

# sethome
# number of homes per player
homes: 1
# player has reached max number of homes
maxHomes: "&cYou have reached the max amount of homes!"
# player sets home without specifying name (doesn't apply for first home)
missingHomeName: "&cUse /sethome <homeName> to set your home."
# player set home successfully
homeSet: "&aHome set successfully."
# home
# home teleport wait time
homeTime: 0
# home wait time message
homeWait: "&bYou will be teleported in {TIME} seconds."
# use {TIME} to display the time in seconds.
# player does not have a home
noHomes: "&cYou must set your home first."
# player gets teleported to home
tpHome: "&aSuccessfully teleported to your home."
# requested home not found
homeNotFound: "&cRequested home could not be found."
# delhome
# home deleted
homeRemoved: "&aHome &cDELETED&a successfully."
# player tried deleting while he didn't have one
noHomeToRemove: "&cYou have no homes to remove!"
# player did not specify home he wants to delete
specifyHomeToRemove: "&cYou have to specify home to delete!"
# player tried to delete non-existing home
homeToRemoveNotFound: "&cHome you want to delete does not exist!"
# homes (displays a list of homes)
# player does not have a home
zeroHomes: "&cYou have no homes."
# display homes message
listHomes: "Homes ({NUM}): &a{LIST}"
# use {NUM} to display the number of homes and {LIST} to list all home names

# tpa config
# time after which teleport request will cancel (seconds)
requestSpanTP: 120
# tp wait time
tpaTime: 0
# tp wait time message
tpaWait: "&bYou will be teleported in {TIME} seconds."
# use {TIME} to display the time in seconds.
# player executed command /tpa with 0 arguments
specifyPlayerTP: "&cUse /tpa <playerName> to teleport to player."
# player you are trying to teleport to in not online
playerOfflineTP: "&cPlayer is not online."
# player tries to teleport to himself
cannotSelfTP: "&cYou cannot teleport to yourself."
# player tries to create new teleport request while already having another request pending
alreadyPendingRequestTP: "&cYou already have a pending request."
# pending teleport request timed out
requestTimedOutTP: "&cRequest timed out."
# request has been sent
requestSentTP: "&6Teleport request has been sent to &b{PLAYER}"
# use {PLAYER} to display name of targeted player.
# tpcancel
# player canceled his teleport request
requestCanceledTP: "&6Request canceled successfully."
# player has no request to cancel
nothingToCancelTP: "&cYou have no pending requests."
# tpaccept & tpdeny
# player accepted teleport request
requestAcceptedTP: "&aTeleport request accepted."
# player gets teleported
teleportingTP: "&bTeleporting..."
# player denied teleport request
requestDeniedTP: "&cTeleport request denied."
# player has no requests to accept or deny
noRequestsTP: "&cYou don't have any pending requests."
# your teleport request gets denied
yourRequestDeniedTP: "&cYour teleport request was denied."
# target has blocked teleport requests
playerToggledTP: "&cYou cannot send request to this player."
# tptoggle
# player disables all incoming TP requests
toggleFalse: "&6You have &c&lDISABLED &6incoming teleport requests."
# player enables all incoming TP requests
toggleTrue: "&6You have &a&lENABLED &6incoming teleport requests."
# target player wants to toggle is not online.
toggleNotOnline: "&cCannot find this player."
# player tries to toggle himself XD
cannotToggleSelf: "&c&lAre you stupid?"
# player disables incoming TP requests from target
playerToggleFalse: "&6You have &c&lDISABLED &6incoming teleport requests from &b{PLAYER}"
# use {PLAYER} to display name of targeted player.
# player enables incoming TP requests from target
playerToggleTrue: "&6You have &a&lENABLED &6incoming teleport requests from &b{PLAYER}"
# use {PLAYER} to display name of targeted player.

# back
# back wait time
backTime: 0
# back wait time message
backWait: "&bYou will be teleported in {TIME} seconds."
# use {TIME} to display the time in seconds.
# player gets teleported to previous location.
backTP: "&aTeleported to previous location."
# player has no previous location to teleport to.
noBackTP: "&cYou have no previous location."

# customize the looks of ACCEPT box
acceptBoxTP: "&a&l[ACCEPT]"
# customize the looks of DENY box
denyBoxTP: "&c&l[DENY]"
# message player will receive when someone sends him a teleport request
targetMsgTP: "
&1------------------------------------------\n
&b{PLAYER} &6has sent you a teleport request.\n
&l        {ACCEPT}          {DENY}        \n
&1------------------------------------------
"
# use {PLAYER} to display PLAYER name of sender
# use {ACCEPT} to display ACCEPT Box
# use {DENY} to display DENY Box
# use \n to create new line

# setwarp
# player sets warp without specifying name
specifyWarp: "&cUse /setwarp <warpName> to set a warp."
# player set warp successfully
warpSet: "&aWarp set successfully."
# player tries to create a warp with a name that already exists
warpAlreadyExists: "&cWarp already exists."
# warp
# warp teleport wait time
warpTime: 0
# warp wait time message
warpWait: "&bYou will be teleported in {TIME} seconds."
# use {TIME} to display the time in seconds.
# player gets teleported to warp.
tpWarp: "&aSuccessfully teleported to a warp."
# requested home not found
warpNotFound: "&cRequested warp could not be found."
# delwarp
# warp deleted
warpRemoved: "&aWarp &cDELETED&a successfully."
# player did not specify warp he wants to delete
specifyWarpToRemove: "&cYou have to specify warp to delete!"
# player tries to delete warp he doesn't own
cannotRemoveWarp: "&cYou cannot remove this warp."
# player tried to delete non-existing warp
warpToRemoveNotFound: "&cWarp you want to delete does not exist!"
# warps (displays a list of warps)
# There are no warps set.
zeroWarps: "&cThere are no warps set."
# display warps message
listWarps: "Warps ({NUM}): &a{LIST}"
# use {NUM} to display the number of homes and {LIST} to list all home names

# cancel teleport on movement
cancelTPOnMove: true # true or false
cancelTPMSG: "&cTeleport have been canceled because you have moved."
# target is not online
playerNotOnline: "&cPlayer is not online."

# allow flight
flyTrue: "&6Flight has been &a&lEnabled"
# disable flight
flyFalse: "&6Flight has been &c&lDisabled"
# allow flight for player
flyTruePlayer: "&6Flight has been &a&lEnabled &6 for {PLAYER}"
# use {PLAYER} to display name of targeted player.
# disable flight for player
flyFalsePlayer: "&6Flight has been &c&lDisabled &6 for {PLAYER}"
# use {PLAYER} to display name of targeted player.
# allow god mode
godTrue: "&6God mode has been &a&lEnabled"
# disable god mode
godFalse: "&6God mode has been &c&lDisabled"
# allow god mode for player
godTruePlayer: "&6God mode has been &a&lEnabled &6 for {PLAYER}"
# use {PLAYER} to display name of targeted player.
# disable god mode for Player
godFalsePlayer: "&6God mode has been &c&lDisabled &6 for {PLAYER}"
# use {PLAYER} to display name of targeted player.
# you get healed
healed: "&aYou have been healed"
# player gets healed
healedPlayer: "&6{PLAYER}&a has been healed"
# use {PLAYER} to display name of targeted player.
# you get fed
fed: "&aYou have been fed."
# player gets fed
fedPlayer: "&6{PLAYER}&a has been fed."
# use {PLAYER} to display name of targeted player.
# enable vanish
vanishTrue: "&6You are &a&oInvisible"
# disable vanish
vanishFalse: "&6You are &c&oVisible"
# enable vanish for player
vanishTruePlayer: "&6{PLAYER}&6 is &a&oInvisible"
# use {PLAYER} to display name of targeted player.
# disable vanish for player
vanishFalsePlayer: "&6{PLAYER}&6 is &c&oVisible"
# use {PLAYER} to display name of targeted player.

# invsee
# player didn't specify target
noArgsInvsee: "&cUse /invsee <playerName> to see someones inventory."
# target cannot be self
noSelfInvsee: "&cPress &lE"

# Spawn command messages
# spawn teleport wait time
spawnTime: 0
# spawn wait time message
spawnWait: "&bYou will be teleported in {TIME} seconds."
# use {TIME} to display the time in seconds.
# set spawn command
setSpawn: "&aSpawn set successfully."
# teleport to spawn
teleportedToSpawn: "&aTeleported to spawn."
# couldn't teleport to spawn because spawn does not exist
spawnNotExist: "&cSpawn does not exist!"