name: Supplements
version: '${project.version}'
main: me.ganyganyant.supplements.Supplements
api-version: 1.18
authors: [ Gany_Ganyant ]
description: Just a simple plugin
commands:
  kys:
    description: Kill Yourself
    usage: /<command>
  discord:
    description: Discord URL
    usage: /<command>
  setspawn:
    description: Set world spawn.
    usage: /<command>
    permission: op
  spawn:
    description: Teleport to world spawn.
    usage: /<command>
  sethome:
    description: Set a home.
    usage: /<command> {home name}
  home:
    description: Teleport to your home.
    usage: /<command> {home name}
  delhome:
    description: Delete your home.
    usage: /<command> {home name}
  homes:
    description: Show list of homes.
    usage: /<command>