name: Supplements
version: '${project.version}'
main: me.ganyganyant.supplements.Supplements
api-version: 1.18
authors: [ Gany_Ganyant ]
description: Just a simple plugin
commands:
  kys:
    description: Kill Yourself
    usage: /<command>
    permission: supplements.kys
  discord:
    description: Discord URL
    usage: /<command>
    permission: supplements.discord
  setspawn:
    description: Set world spawn.
    usage: /<command>
    permission: supplements.setspawn
  spawn:
    description: Teleport to world spawn.
    usage: /<command>
    permission: supplements.spawn
  sethome:
    description: Set a home.
    usage: /<command> {home name}
    permission: supplements.home
  home:
    description: Teleport to your home.
    usage: /<command> {home name}
    permission: supplements.home
  delhome:
    description: Delete your home.
    usage: /<command> {home name}
    permission: supplements.home
  homes:
    description: Show list of homes.
    usage: /<command>
    permission: supplements.home
  tpa:
    description: Send teleport request to a player.
    usage: /<command>
    permission: supplements.tpa
  tpaccept:
    description: Accept teleport request.
    usage: /<command>
    permission: supplements.tpa
  tpdeny:
    description: Deny teleport request.
    usage: /<command>
    permission: supplements.tpa
  tpcancel:
    description: Cancel pending request.
    usage: /<command>
    permission: supplements.tpa
  tpall:
    description: Teleport all players to yourself.
    usage: /<command>
    permission: supplements.tpall
  tptoggle:
    description: Toggle teleport requests.
    usage: /<command> {Player}
    permission: supplements.tptoggle
  back:
    description: Teleport to previous location.
    usage: /<command>
    permission: supplements.back
  fly:
    description: Toggle flight.
    usage: /<command>
    permission: supplements.fly
  god:
    description: Toggle Invincibility.
    usage: /<command>
    permission: supplements.god
  heal:
    description: Heal yourself.
    usage: /<command>
    permission: supplements.heal
  feed:
    description: Fill your hungerbar.
    usage: /<command>
    permission: supplements.feed
  vanish:
    description: Sets you invisible to other players.
    usage: /<command>
    permission: supplements.vanish
  invsee:
    description: Open inventory of player.
    usage: /<command>
    permission: supplements.invsee
  warp:
    description: Warp to a location.
    usage: /<command> {warp name}
    permission: supplements.warp
  setwarp:
    description: Create a warp.
    usage: /<command> {warp name}
    permission: supplements.warp.set
  delwarp:
    description: Delete a warp.
    usage: /<command> {warp name}
    permission: supplements.warp.del
  warps:
    description: Show list of warps.
    usage: /<command>
    permission: supplements.warp
  fix:
    description: Repair item in main hand.
    usage: /<command>
    permission: supplements.fix
permissions:
  supplements.*:
    default: op
  supplements.kys:
    default: true
  supplements.discord:
    default: true
  supplements.setspawn:
    default: op
  supplements.spawn:
    default: true
  supplements.home:
    description: Allows all home commands.
    default: true
  supplements.tpa:
    description: Allows all tpa commands excluding tpall and tptoggle.
    default: true
  supplements.tpall:
    default: op
  supplements.passengerTp:
    default: op
  supplements.tptoggle:
    default: true
  supplements.back:
    default: true
  supplements.fly:
    default: op
  supplements.fly.player:
    default: op
  supplements.god:
    default: op
  supplements.god.player:
    default: op
  supplements.heal:
    default: op
  supplements.heal.player:
    default: op
  supplements.feed:
    default: op
  supplements.feed.player:
    default: op
  supplements.vanish:
    default: op
  supplements.vanish.player:
    default: op
  supplements.invsee:
    default: op
  supplements.warp:
    default: true
  supplements.warp.set:
    default: op
  supplements.warp.del:
    default: op
  supplements.warps:
    default: true
  supplements.warp.delany:
    default: op
  supplements.fix:
    default: op